name: Docker Build

on:
  push:
    branches: [main]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Build Docker image
        run: |
          docker build -t devops-learning-flask ./compose/app
      - name: Show images
        run: docker images
